[package]
name = "mini-rust"
version = "0.1.0"
authors = ["Funkschy <felixschoeller@outlook.de>"]
edition = "2018"
description = "A compiler for a small subset of the Rust programming language"
keywords = ["compiler", "rust", "parser"]

[dependencies]
ansi_term = "0.11"
unicode-width = "0.1.5"
